### PR TITLE
Track boat location for scenery + NPCs

### LINKED ISSUE #71: NPE thrown when getting onto a boat
```
[Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: Cannot invoke "net.runelite.api.coords.LocalPoint.getWorldView()" because "localPoint" is null
	at net.runelite.api.coords.WorldPoint.fromLocalInstance(WorldPoint.java:243)
	at com.Crowdsourcing.scenery.CrowdsourcingScenery.addObjectThisTick(CrowdsourcingScenery.java:81)
	at com.Crowdsourcing.scenery.CrowdsourcingScenery.onGameObjectSpawned(CrowdsourcingScenery.java:108)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:215)
	at jh.ja(jh.java:6004)
	at jh.iy(jh.java:36227)
	at client.gv(client.java:63931)
	at client.yh(client.java:40319)
	at client.qc(client.java)
	at client.qs(client.java:12648)
	at client.bf(client.java:11642)
	at bm.bo(bm.java:463)
	at bm.ya(bm.java)
	at bm.run(bm.java:65390)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Immediately thrown and spammed once I board my boat

### PR DESCRIPTION
**Pull request by samszotkowski**
NPCs and scenery can spawn on boats too, get proper location for them. I believe the point this returns is the tile that the boat's center of rotation intersects? Something like that. Which means we don't actually know the *exact* tile of a boat NPC/scenery, just roughly where the boat is when some event happens involving the entity on the boat.

I don't think we generally care for more detail than that, really. If we really want to know where something like a cargo hold spawns in the boat's coordinate system, that's something we could do, but we'd do it separately.

Accounting for scenery on boats fixes #71

### CODE REVIEW

File: src/main/java/com/Crowdsourcing/scenery/CrowdsourcingScenery.java [hunk 1]
```diff
@@ -78,7 +79,11 @@ private void addObjectThisTick(SceneryEventType type, WorldPoint baseLocation, i
 			}
 		}
 		LocalPoint local = LocalPoint.fromWorld(client, baseLocation);
-		WorldPoint location = WorldPoint.fromLocalInstance(client, local);
+		if (local == null)
+		{
+			return;
+		}
+		WorldPoint location = BoatLocation.fromLocal(client, local);
```
Comment (andmcadams) [inline src/main/java/com/Crowdsourcing/scenery/CrowdsourcingScenery.java]: Should you return here? This seems like a slight behavior change since with this change we would not send an event if location is null (the fromLocal fn should handle this case anyway). If there's a reason this case is different, that's fine, just doesn't seem obvious that it should be different than the cases above that happily send null locations

```suggestion
		WorldPoint location = BoatLocation.fromLocal(client, local);
```

**Review by andmcadams — CHANGES_REQUESTED** [review]

File: src/main/java/com/Crowdsourcing/scenery/CrowdsourcingScenery.java (hunk 1 above)
Comment (samszotkowski) [reply src/main/java/com/Crowdsourcing/scenery/CrowdsourcingScenery.java]: I have no idea why scenery seems to be the odd one out in being okay with storing a null location, but I've removed that bit so behavior doesn't change
